default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: products_db
  username: postgres
  password: postgres

development:
  <<: *default
  database: products_service_development

test:
  <<: *default
  database: products_service_test

production:
  <<: *default
  database: products_service_production
